baseURL = "/"
languageCode = "en-us"
title = "HC Swimsite"
#theme = "ga-hugo-theme"
club_email = "hcswimclub@hotmail.com"
club_phone = "03 6211 4919"
[taxonomies]
#	tag = "tags"
#	category = "categories"
	event_type = "event_types"
	person = "people"
	squad = "squads"
	role = "roles"
	pool = "pools"
	topic = "topics"

[params]
	css_sitecentre = " w-80 center pt3 pb3"
	css_card = " dark-blue ba b f5 ma2 pa2 bw1 br3 "
	css_navclass_a = " link dark-blue underline-hover "
	css_list_card = " ba br2 pa2 bg-lightest-blue"
	css_navcard = "link green f3 b bb bw2 hover-dark-blue"
	css_cardtitle = " f3 pb2 v-mid"
#	css_cardlink = "link dim dark-blue"
	css_cardlink = "link near-white f3 b dib bb bw2 hover-green"
	css_homepagelink = " link db black hover-dark-blue "
	css_homepagecard = " br3 bw1 ba ma2 bg-animate hover-bg-white"
	css_taxolink = " link underline blue hover-green "
