backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
site_url: https://relaxed-wescoff-a7f5a3.netlify.com/
display_url: https://relaxed-wescoff-a7f5a3.netlify.com/
media_folder: "static/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "club" # Used in routes, e.g., /admin/collections/blog
    label: "Club" # Used in the UI
    folder: "content/club" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "club-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Topics", name: "topics", widget: "select", options: ["Club","Progression"], required: false, multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "events-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "News", name: "news", widget: "boolean"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "text"}
      - {label: "Expiry Date", name: "expirydate", widget: "date"}
      - {label: "Enter By", name: "entries_close", widget: "datetime", required: false}
      - {label: "Event Type", name: "event_types", widget: "select", options: ["Swim Meets","Training","Swim Camps","Committee","Time Trials","Land Based Training","Socials","Club"], required: false, multiple: true}
      - {label: "Pool", name: "pools", widget: "select", options: ["Collegiate","Hobart Aquatic Centre","Launceston Acquatic Centre"], required: false, multiple: true}
      - {label: "Course", name: "courses", widget: "select", options: ["Long","Short"], required: false, multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "people"
    label: "People"
    folder: "content/people"
    create: true
    slug: "people-{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Phone", name: "phone", widget: "string", required: false}
      - {label: "Joined", name: "joined", widget: "date", required: false}
      - {label: "Photo", name: "photo", widget: "image", required: false, allow_multiple: false}
      - {label: "Role", name: "roles", widget: "select", options: ["Coaches","Committee","Contacts"], required: false, multiple: true}
      - {label: "Rank", name: "rank", widget: "select", options: ["President","Vice President","Head Coach","Club Captain","Main Contact"], required: false, multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "squads"
    label: "Squads"
    folder: "content/squads"
    create: true
    slug: "squads-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Squad", name: "squad", widget: "select", options: ["Target","Senior State","State","Development","Junior","Junior Racers"], required: false, multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}

